// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"database/sql"

	"github.com/gin-gonic/gin"
	"github.com/shige1114/job/backend/internal/account/infrastructure/api"
	"github.com/shige1114/job/backend/internal/account/infrastructure/persistence"
	"github.com/shige1114/job/backend/internal/account/interface/handler"
	"github.com/shige1114/job/backend/internal/account/interface/presenter"
	"github.com/shige1114/job/backend/internal/account/usecase"
)

// Injectors from wire.go:

// InitializeRouter は依存関係を解決してルーターを初期化します
func InitializeRouter(db *sql.DB) *gin.Engine {
	applicationRepository := persistence.NewSqliteApplicationRepository(db)
	userRepository := persistence.NewSqliteUserRepository(db)
	findSameEmailService := persistence.NewFindSameEmailService(applicationRepository, userRepository)
	registerApplicationUseCase := usecase.NewRegisterApplicationUseCase(applicationRepository, findSameEmailService)
	registerApplicationPresenter := presenter.NewRegisterApplicationPresenter()
	registerApplicationHandler := handler.NewRegisterApplicationHandler(registerApplicationUseCase, registerApplicationPresenter)
	engine := api.NewRouter(registerApplicationHandler)
	return engine
}
