// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	CreateApplication(ctx context.Context, arg CreateApplicationParams) error
	DeleteApplication(ctx context.Context, id string) error
	GetApplication(ctx context.Context, id string) (Application, error)
	GetApplicationByEmail(ctx context.Context, email string) (Application, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	UpdateApplication(ctx context.Context, arg UpdateApplicationParams) error
}

var _ Querier = (*Queries)(nil)
