// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
	"time"
)

const createApplication = `-- name: CreateApplication :exec
INSERT INTO applications (id, email, code, expires_at)
VALUES (?, ?, ?, ?)
`

type CreateApplicationParams struct {
	ID        string    `json:"id"`
	Email     string    `json:"email"`
	Code      string    `json:"code"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreateApplication(ctx context.Context, arg CreateApplicationParams) error {
	_, err := q.db.ExecContext(ctx, createApplication,
		arg.ID,
		arg.Email,
		arg.Code,
		arg.ExpiresAt,
	)
	return err
}

const deleteApplication = `-- name: DeleteApplication :exec
DELETE FROM applications
WHERE id = ?
`

func (q *Queries) DeleteApplication(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteApplication, id)
	return err
}

const getApplication = `-- name: GetApplication :one
SELECT id, email, code, expires_at FROM applications
WHERE id = ? LIMIT 1
`

func (q *Queries) GetApplication(ctx context.Context, id string) (Application, error) {
	row := q.db.QueryRowContext(ctx, getApplication, id)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Code,
		&i.ExpiresAt,
	)
	return i, err
}

const getApplicationByEmail = `-- name: GetApplicationByEmail :one
SELECT id, email, code, expires_at FROM applications
WHERE email = ? LIMIT 1
`

func (q *Queries) GetApplicationByEmail(ctx context.Context, email string) (Application, error) {
	row := q.db.QueryRowContext(ctx, getApplicationByEmail, email)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Code,
		&i.ExpiresAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password FROM users
WHERE email = ? LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(&i.ID, &i.Email, &i.Password)
	return i, err
}

const updateApplication = `-- name: UpdateApplication :exec
UPDATE applications
SET email = ?, code = ?, expires_at = ?
WHERE id = ?
`

type UpdateApplicationParams struct {
	Email     string    `json:"email"`
	Code      string    `json:"code"`
	ExpiresAt time.Time `json:"expires_at"`
	ID        string    `json:"id"`
}

func (q *Queries) UpdateApplication(ctx context.Context, arg UpdateApplicationParams) error {
	_, err := q.db.ExecContext(ctx, updateApplication,
		arg.Email,
		arg.Code,
		arg.ExpiresAt,
		arg.ID,
	)
	return err
}
