// Code generated by MockGen. DO NOT EDIT.
// Source: internal/account/domain/service/find_same_email.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/shige1114/job/backend/internal/account/domain/model"
)

// MockFindSameEmailService is a mock of FindSameEmailService interface.
type MockFindSameEmailService struct {
	ctrl     *gomock.Controller
	recorder *MockFindSameEmailServiceMockRecorder
}

// MockFindSameEmailServiceMockRecorder is the mock recorder for MockFindSameEmailService.
type MockFindSameEmailServiceMockRecorder struct {
	mock *MockFindSameEmailService
}

// NewMockFindSameEmailService creates a new mock instance.
func NewMockFindSameEmailService(ctrl *gomock.Controller) *MockFindSameEmailService {
	mock := &MockFindSameEmailService{ctrl: ctrl}
	mock.recorder = &MockFindSameEmailServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFindSameEmailService) EXPECT() *MockFindSameEmailServiceMockRecorder {
	return m.recorder
}

// Exists mocks base method.
func (m *MockFindSameEmailService) Exists(ctx context.Context, email model.Email) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exists", ctx, email)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exists indicates an expected call of Exists.
func (mr *MockFindSameEmailServiceMockRecorder) Exists(ctx, email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exists", reflect.TypeOf((*MockFindSameEmailService)(nil).Exists), ctx, email)
}
